### ISSUE TITLE
[Feature] Entity 생성

### ISSUE THREAD

**Issue by junseoplee** [junseoplee/spring-blog#1]
## 📑 작업 사항
Entity 생성

## To-do
- [x] BaseEntity 생성
- [x] User Entity 생성
- [x] Article Entity 생성
- [x] Comment Entity 생성
