### ISSUE TITLE
[Feature] 회원 탈퇴 구현

### ISSUE THREAD

**Issue by junseoplee** [junseoplee/spring-blog#17]
## 📑 작업 사항
회원 탈퇴 기능 구현 및 테스트
완성된 API 명세 정리

## To-do
- [x] 회원 탈퇴 기능 구현
- [x] 회원 탈퇴 테스트
- [x] API 명세 정리

## ETC
